name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      # - name: Install dependencies
      #   run: go get .

      - name: Test
        run: go test ./test -v # -json > TestReults.json for json test results

      # optional uploading of json
      # - name: Upload Go test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Go-results-${{ matrix.go-version }}
      #     path: TestResults-${{ matrix.go-version }}.json